#!/usr/bin/env python3
"""Run the benchmarks on both cores (and on pipelined-core variants) and
print a Markdown report.  Called by `make bench`, which builds everything
first; every simulator run is in lockstep with the golden model, so a
number is only reported for a run whose every instruction was checked.

Numbers come from the core's own counters around each benchmark's timed
region (the program prints them), not from the simulator.
"""

import json
import platform
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
B = REPO / "build"

# (label, simulator, description)
CONFIGS = [
    ("single", "vsim_single", "core A, single cycle, ideal memory"),
    ("pipe", "vsim_pipe", "core B default: I$ 4 KiB DM, D$ 4 KiB 2-way WB, BTB 128 + BHT 256 + RAS 8, memory latency 10"),
    ("pipe-nobp", "vsim_pipe-nobp", "core B, predictor off (always not taken)"),
    ("pipe-noras", "vsim_pipe-noras", "core B, no return-address stack"),
    ("pipe-ic8k", "vsim_pipe-ic8k", "core B, 8 KiB I-cache"),
    ("pipe-lat1", "vsim_pipe-lat1", "core B, memory latency 1 cycle"),
    ("pipe-lat30", "vsim_pipe-lat30", "core B, memory latency 30 cycles"),
]
PROGRAMS = [("coremark", "build/sw/coremark-bench.elf"), ("dhrystone", "build/sw/dhrystone.elf")]
COREMARK_ITER = 40
DHRYSTONE_RUNS = 500
LINE = re.compile(r"^\[(\w+)\] (.*)$")


def run(sim, elf):
    p = subprocess.run([str(B / sim), str(REPO / elf)], capture_output=True, text=True, cwd=REPO, timeout=3600)
    if p.returncode != 0:
        sys.exit(f"{sim} {elf}: exit {p.returncode}\n{p.stderr[-2000:]}")
    stats = {}
    for line in p.stdout.splitlines():
        m = LINE.match(line)
        if m:
            for kv in m.group(2).split():
                k, v = kv.split("=")
                stats[k] = float(v)
    return stats, p.stdout


def pct(a, b, digits=1):
    return f"{100.0 * a / b:.{digits}f}%" if b else "n/a"


def sta_ns(core):
    f = B / "synth" / core / "sta.txt"
    m = re.search(r"Latest arrival time in '\S+' is (\d+)", f.read_text()) if f.exists() else None
    return int(m.group(1)) / 1000 if m else None


def main():
    results = {}
    for label, sim, _ in CONFIGS:
        for prog, elf in PROGRAMS:
            stats, out = run(sim, elf)
            results[(label, prog)] = stats
            if prog == "coremark" and label == "pipe":
                results["coremark_out"] = out
            print(f"{label:10s} {prog:10s} cycles={stats['cycles']:.0f} CPI={stats['CPI']:.3f}", file=sys.stderr)

    o = ["# Benchmark results", "",
         "Generated by `make bench` (tools/bench.py).  Every run is in lockstep with the golden model.",
         f"Host: {platform.machine()}, {platform.system()} {platform.release()}; simulator: Verilator.",
         "Measured on a shared machine; the numbers are simulated cycle counts, so host load does not change them.",
         "", "Counters are read by the program around the timed region: CoreMark's "
         f"{COREMARK_ITER} iterations, Dhrystone's {DHRYSTONE_RUNS} runs.", ""]
    o += ["| Configuration | Program | Cycles | Instructions | CPI | Score per MHz | Branch pred. | Jump pred. | "
          "I$ hit | D$ hit | Load-use bubbles |", "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for label, _, _ in CONFIGS:
        for prog, _ in PROGRAMS:
            s = results[(label, prog)]
            if prog == "coremark":
                score = f"{COREMARK_ITER * 1e6 / s['cycles']:.3f} CM/MHz"
            else:
                score = f"{1e6 / (s['cycles'] / DHRYSTONE_RUNS) / 1757:.3f} DMIPS/MHz"
            single = label == "single"
            o.append("| {} | {} | {:,.0f} | {:,.0f} | {:.3f} | {} | {} | {} | {} | {} | {:,.0f} |".format(
                label, prog, s["cycles"], s["instret"], s["CPI"], score,
                "n/a" if single else pct(s["branches"] - s["branch_mispredicts"], s["branches"]),
                "n/a" if single else pct(s["jumps"] - s["jump_mispredicts"], s["jumps"]),
                "n/a" if single else pct(s["icache_accesses"] - s["icache_misses"], s["icache_accesses"], 2),
                "n/a" if single else pct(s["dcache_accesses"] - s["dcache_misses"], s["dcache_accesses"], 2),
                s["load_use_stalls"]))
    o += ["", "Configurations:", ""]
    o += [f"- `{label}`: {desc}" for label, _, desc in CONFIGS]
    o += ["", "Cycle ratio, single-cycle / pipelined (default):", ""]
    for prog, _ in PROGRAMS:
        a, b = results[("single", prog)]["cycles"], results[("pipe", prog)]["cycles"]
        o.append(f"- {prog}: {a:,.0f} / {b:,.0f} = {a / b:.3f} (the pipelined core needs {b / a:.2f}x the cycles)")
    ta, tb = sta_ns("single"), sta_ns("pipe")
    if ta and tb:
        o += ["", f"Estimated run time with the logic-only path delays from `make sta` (core A {ta:.1f} ns, "
                  f"core B {tb:.1f} ns; no routing, not timing sign-off, see synth/report.md):", ""]
        for prog, _ in PROGRAMS:
            a, b = results[("single", prog)]["cycles"] * ta, results[("pipe", prog)]["cycles"] * tb
            o.append(f"- {prog}: {a / 1e6:.2f} ms vs {b / 1e6:.2f} ms, pipelined core about {a / b:.1f}x faster")
    o += ["", "CoreMark's own report on the pipelined core (default configuration):", "", "```"]
    o += [l for l in results["coremark_out"].splitlines() if not l.startswith("[")]
    o += ["```"]
    print("\n".join(o))
    (B / "bench.json").write_text(json.dumps({f"{k[0]}/{k[1]}": v for k, v in results.items()
                                              if isinstance(k, tuple)}, indent=1))


if __name__ == "__main__":
    main()
