#!/usr/bin/env python3
"""Floating-point benchmark report (`make fp-bench`).

Runs sw/bench/fpbench three ways, every run in lockstep with the golden
model:

    soft      RV32IM code calling compiler-rt's soft-float routines, on core B
    hard      RV32IMFD code, on core B with the FPU (-ffp-contract=off)
    hard-fma  the same with a*b+c contracted into fused multiply-adds

and prints a Markdown report: cycles and speed-up per kernel, the cost of
single operations, and the FPU's latency per operation as measured by the
unit testbench.  The soft and hard builds perform the same IEEE operations,
so their checksums must be equal; the tool fails if they are not.
"""

import platform
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
B = REPO / "build"
RUNS = [("soft", "vsim_pipe", "build/sw/fpbench-soft.elf"),
        ("hard", "vsim_pipe_fd", "build/sw/fpbench-hard.elf"),
        ("hard-fma", "vsim_pipe_fd", "build/sw/fpbench-fma.elf")]
KERNELS = [("nbody", "8 bodies, 12 leapfrog steps (mul, add, div, sqrt)"),
           ("lu", "20 x 20 LU factorisation with pivoting, and solve"),
           ("poly", "degree-12 polynomial by Horner's rule, 400 points"),
           ("mandel", "Mandelbrot escape counts, 24 x 12 points"),
           ("fir", "32-tap FIR filter, 400 samples, single precision"),
           ("total", "all five")]
OPS = [("add", "a + b"), ("mul", "a * b"), ("div", "a / b"), ("sqrt", "square root"), ("cmp", "a < b"),
       ("i2d", "int to double"), ("d2i", "double to int")]


def run(sim, elf):
    p = subprocess.run([str(B / sim), "--stats", str(REPO / elf)], capture_output=True, text=True, cwd=REPO,
                       timeout=3600)
    if p.returncode != 0:
        sys.exit(f"{sim} {elf}: exit {p.returncode}\n{p.stderr[-2000:]}")
    stats, sums = {}, {}
    for line in p.stdout.splitlines():
        m = re.match(r"^\[(\w+)\] (.*)$", line)
        if m:
            stats[m.group(1)] = {k: int(v) for k, v in (kv.split("=") for kv in m.group(2).split())}
        m = re.match(r"^(\w+) checksum=(\w+)$", line)
        if m:
            sums[m.group(1)] = m.group(2)
    return stats, sums


def main():
    res = {}
    for label, sim, elf in RUNS:
        res[label] = run(sim, elf)
        print(f"{label:9s} total cycles {res[label][0]['total']['cycles']:,}", file=sys.stderr)
    soft, hard, fma = (res[k][0] for k in ("soft", "hard", "hard-fma"))
    if res["soft"][1] != res["hard"][1]:
        sys.exit(f"checksums differ between soft and hard float:\n{res['soft'][1]}\n{res['hard'][1]}")

    o = ["# Floating-point benchmark", "",
         "Generated by `make fp-bench` (tools/fpbench.py).  Every run is in lockstep with the golden model.",
         f"Host: {platform.machine()}, {platform.system()} {platform.release()}; simulator: Verilator.",
         "The numbers are simulated cycle counts read from the core's own counters, so host load does not change them.",
         "", "`sw/bench/fpbench` built three ways: **soft** = RV32IM with compiler-rt's soft-float routines, on core B; "
         "**hard** = RV32IMFD on core B with the FPU, `-ffp-contract=off`; **hard-fma** = the same with "
         "`-ffp-contract=fast` (a*b+c becomes one fused multiply-add).  Memory latency 10 cycles, default caches.",
         "", "| Kernel | soft cycles | soft CPI | hard cycles | hard CPI | speed-up | hard-fma cycles | speed-up |",
         "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for k, _ in KERNELS:
        s, h, f = soft[k], hard[k], fma[k]
        o.append(f"| {k} | {s['cycles']:,} | {s['cycles'] / s['instret']:.2f} | {h['cycles']:,} | "
                 f"{h['cycles'] / h['instret']:.2f} | {s['cycles'] / h['cycles']:.1f}x | {f['cycles']:,} | "
                 f"{s['cycles'] / f['cycles']:.1f}x |")
    o += ["", "Kernels:", ""] + [f"- `{k}`: {d}" for k, d in KERNELS]
    same = ", ".join(f"{k} {v}" for k, v in res["hard"][1].items())
    o += ["", f"Result checksums (bit patterns), identical for soft and hard: {same}.",
          "hard-fma rounds each a*b+c once instead of twice, so its results differ in the last bits: "
          + ", ".join(f"{k} {v}" for k, v in res["hard-fma"][1].items()) + ".", ""]

    o += ["## Cost of one operation", "",
          "One operation per element of a 64-entry array of doubles, 8 passes: cycles per element, minus the "
          "cycles of a loop that only copies (so what remains is the operation plus the extra operand load).", "",
          "| Operation | soft: cycles per element | hard: cycles per element | ratio |", "|---|---:|---:|---:|"]
    cs, ch = soft["op_copy"]["per_element_x100"], hard["op_copy"]["per_element_x100"]
    for k, d in OPS:
        a = (soft[f"op_{k}"]["per_element_x100"] - cs) / 100
        b = (hard[f"op_{k}"]["per_element_x100"] - ch) / 100
        o.append(f"| {d} | {a:,.1f} | {b:.1f} | {a / b:.0f}x |")
    o += ["", f"(The copy loop itself: {cs / 100:.1f} cycles per element soft, {ch / 100:.1f} hard, where each "
          "8-byte load or store is two word accesses.  The soft square root is the benchmark's own "
          "digit-by-digit routine, since compiler-rt has none.)", ""]

    tb = B / "fpu_tb"
    if tb.exists():
        p = subprocess.run([str(tb), "--random", "300000", "1"], capture_output=True, text=True)
        if p.returncode != 0:
            sys.exit("fpu_tb --random failed:\n" + p.stdout[-2000:] + p.stderr[-2000:])
        o += ["## FPU latency", "",
              "Clock cycles an instruction spends in EX, measured by the unit testbench over 300,000 random "
              "operations (`build/fpu_tb --random 300000 1`, operands biased toward special values).  The count "
              "depends on the operands: 2 cycles when the result needs no arithmetic (a NaN, an infinity, a zero "
              "divisor...), and divide and square root normalise a subnormal operand one bit per cycle first "
              "(the long end of their range).", ""]
        o += [l for l in p.stdout.splitlines() if l.startswith("|")]
    print("\n".join(o))


if __name__ == "__main__":
    main()
